<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 26/01/2018
 * Time: 11:11 AM
 */
/** @var Exception $ex */
/** @var $code */
if ($code >= 500) {
    $message = 'Ha ocurrido un error. Contacte al desarrollador.';
} elseif ($code >= 400) {
    $message = $ex->getMessage();
}
$trace = Globales::json_encode($ex->getTrace());
?>
<label for="trace">
    <textarea style="display: none" id="trace"><?= $trace ?></textarea>
</label>
<h2><?= $code ?></h2>
<h3><?= $message ?? '' ?></h3>
<a href="?s=1">Cerrar Sesión</a>
<script>
    console.error(
        "<?= addslashes($ex->getMessage()) ?>",
        "<?= $ex->getFile() ?>",
        <?= $ex->getLine() ?>,
        JSON.parse(document.getElementById('trace').textContent));
</script>
