<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 06/abr/2017
 * Time: 06:02 PM
 */
$this->idioma = Globales::getIdioma('floating');
$hidden = "";
if($_SESSION["sistema"] == 'educacion')
{
    if($_SESSION['perfil'] == 2 or $_SESSION['perfil'] == 3)
        $hidden = 'hidden';
}

$valNomina = false;
switch (TYPE_SYSTEM)
{
    case "produccion":
        $valNomina = true;
    break;
}
?>
<div class="<?=$hidden?>">
    <a id="btnFlotante" class="floatingButton md-btn md-fab md-fab-bottom-right pos-fix btn-primary">
        <i class="material-icons i-24 text-white">add</i>
    </a>
    <div class="quickMenu animated fadeInUp hidden" id="quickMenu" data-backdrop="false">
        <div class="right" style="width: 207px">
            <div class="box">
                <div class="box-body" id="floatingMenu">
                    <?php
                        if ($_SESSION["namespace"] != "distribuidor\\")
                        {
                            foreach ($this->metadata->floating as $index => $button):
                    ?>
                                <div>
                                    <span style="cursor: pointer" onclick="<?= $button->onclick ?>" class="label label-lg <?= $button->color ?>"><?= $this->idioma->btn[$index] ?></span>
                                </div>
                    <?php
                            endforeach;

                            if($valNomina)
                            {
                    ?>
                                <div>
                                    <span style="cursor: pointer" onclick="aside('ventas', 'pago', {})" class="label label-lg teal">Pago n&oacute;mina</span>
                                </div>
                    <?php
                            }
                        }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
