<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 27/feb/2017
 * Time: 05:37 PM
 */
/** @var Perfiles $this */
?>
<div class="padding">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="table-responsive">
                    <table class="table table-striped b-t b-b">
                        <thead>
                        <tr>
                            <th><?= $this->idioma->lblNombre ?></th>
                            <th style="width: 1px"><?= $this->idioma->lblAcciones ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?= $this->tablaPerfiles ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
