<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 23/feb/2017
 * Time: 02:18 PM
 */
/**
 * @var Usuarios $this
 */
?>
<div class="padding">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="table-responsive">
                    <table class="table table-striped b-t b-b">
                        <thead>
                        <tr>
                            <th><?= $this->idioma->lblNombre ?></th>
                            <th><?= $this->idioma->lblUsuario ?></th>
                            <th>rep</th>
                            <th><?= $this->idioma->lblPerfil ?></th>
                            <th style="width: 1px"><?= $this->idioma->lblAcciones ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?= $this->tablaUsuarios ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>