<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 20/feb/2017
 * Time: 01:04 PM
 */
/** @var Control $this */
?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8"/>
    <title><?= $this->metadata->app_name ?></title>
    <meta name="description" content="Admin, Dashboard, Bootstrap, Bootstrap 4, Angular, AngularJS"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimal-ui"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- for ios 7 style, multi-resolution icon of 152x152 -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-barstyle" content="black-translucent">
    <link rel="apple-touch-icon"
        <?php $ruta = HTTP_PATH_ROOT . "recursos/img/logo.png";
        if (!file_exists($ruta)) $ruta = "../framework/recursos/img/logo.png"; ?>

          href="<?= $ruta ?>">
    <meta name="apple-mobile-web-app-title" content="Flatkit">
    <!-- for Chrome on Android, multi-resolution icon of 196x196 -->
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="shortcut icon" sizes="196x196" href="<?= $ruta ?>">

    <?= $this->stylesheets ?>
    <style>
        .navside {
            background-color: <?=$this->configSistema->color?:'#2e3e4e'?>;
        }

        .text-primary {
            color: <?=$this->metadata->color->buttons->background?:'#cccb2a'?> !important;
        }

        .b-primary {
            border-color: <?=$this->metadata->color->buttons->background?:'#cccb2a'?>;
        }

        .btn.b-primary:focus,
        .btn.b-primary:hover,
        .btn.primary:focus,
        .btn.primary:hover {
            background-color: <?=$this->metadata->color->buttons->background?:'#cccb2a'?>;
            border-color: <?=$this->metadata->color->buttons->background?:'#cccb2a'?>;
            color: white !important;
        }

        .btn-primary,
        .btn-primary:hover,
        .btn-primary:active:hover,
        .btn-primary:focus {
            background-color: <?=$this->metadata->color->buttons->background?:'#cccb2a'?>;
            border-color: <?=$this->metadata->color->buttons->background?:'#cccb2a'?>;
        }
    </style>
</head>
<body>
<div class="loader">
    <div id="loading">
        <div class="loading-center">
            <div class="loading-center-absolute">
                <div class="object" id="object_one"></div>
                <div class="object" id="object_two"></div>
                <div class="object" id="object_three"></div>
                <div class="object" id="object_four"></div>
                <div class="object" id="object_five"></div>
                <div class="object" id="object_six"></div>
                <div class="object" id="object_seven"></div>
                <div class="object" id="object_eight"></div>
                <div class="object" id="object_big"></div>
            </div>
        </div>
    </div>
</div>
<form id="frmSistema">
    <fieldset id="loader" disabled>
        <link rel="shortcut icon" sizes="196x196" href="/recursos/plugins/flatkit/assets/images/logo.png">
        <div class="app" id="app">
            <?php if ($vista != "login" and $vista != "registro"): ?>
            <!-- ############ LAYOUT START-->
            <!-- aside -->
            <div id="aside" class="app-aside modal fade nav-dropdown">
                <!-- fluid app aside -->
                <div class="left navside dark dk" layout="column">
                    <div class="navbar no-radius">
                        <!-- brand -->
                        <a class="navbar-brand" onclick="navegar('inicio')">
                            <?php
                                $path = "usuario/$_SESSION[token]/config/{$this->configSistema->imagen}";
                            $img = file_exists(APP_ROOT . $path) ? APP_ROOT . $path :(file_exists(HTTP_PATH_ROOT . $path)? HTTP_PATH_ROOT . $path:'../framework/'.$path);
                            if(file_exists($img)):?>
                                <img src="<?= $img ?>"alt="Logo">
                            <?php endif; ?>

                            <span class="hidden-folded inline"><?= $this->configSistema->nombre ?></span>
                        </a>
                        <div>
                            <a onclick="btnMiPerfil()">
                                <span class="nombreUser hidden-folded inline text-muted nav-text"><?= $this->nombreUsuario ?></span></a>
                        </div>
                        <!-- / brand -->
                    </div>
                    <div flex class="hide-scroll">
                        <nav class="scroll nav-light">
                            <ul class="nav" ui-nav style="text-transform: capitalize">
                                <?= $this->modulos ?>
                                <?php if ($_SESSION["namespace"] == "\\"): ?>
                                    <!--<li class="nav-header hidden-folded pagar">
                                    <span class="nav-icon">
                                    </span>
                                        <a onclick="navegar('pago');">
                                            <span class="nav-text">Suscripción</span>
                                        </a>
                                    </li>-->
                                <?php endif; ?>
                            </ul>
                        </nav>
                    </div>
                    <?php if (!empty($this->metadata->help_link)): ?>
                        <div flex-no-shrink class="b-t navside">
                            <div class="nav-header">
                                <span class="nav-icon"><i class="material-icons">help</i></span>
                                <a class="nav-text" href="<?= $this->metadata->help_link ?>"
                                   target="_blank"><?= $this->idioma->sidebar->lblAyuda ?></a>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div flex-no-shrink class="b-t">
                        <div class="nav-fold">
                            <a onclick="location.reload(true)" class="version">v/<?= Globales::getVersion() ?>
                                -<?= $_SESSION[token] ?></a>
                        </div>
                    </div>
                </div>
            </div>
        <!-- / -->
        <!-- content -->
            <div id="content" class="app-content box-shadow-z0" role="main">
                <div class="app-header white box-shadow">
                    <div id="messages" class="animated" style="opacity: 0;display: none;">
                        <ul>
                            <li></li>
                        </ul>
                    </div>
                    <div class="navbar">
                        <ul class="nav navbar-nav">
                            <?php
                            $accion = $this->permisos->crear ? $this->idioma->modulos->{MODULO}[1] : null;
                            ?>
                            <li class="nav-item">
                                <h4 class="navbar-brand"><?= $this->idioma->modulos->{MODULO}[0] ?>
                                    <?php if (!is_null($accion)): ?>
                                        <a onclick="<?= "$accion('$_SESSION[modulo]','nuevo');" ?>"
                                           class="btn btn-sm btn-outline b-primary text-primary b-2x"
                                           data-toggle="dropdown">
                                            <i class="material-icons">add</i>
                                        </a>
                                    <?php endif; ?>
                                </h4>
                            </li>
                        </ul>
                        <!-- Open side - Naviation on mobile -->
                        <a data-toggle="modal" data-target="#aside" id="btnAside"
                           class="btn btn-outline b-primary navbar-item pull-left hidden-lg-up">
                            <img style="width: 20px" src="<?= $ruta ?>"/>
                        </a>
                        <!-- / -->

                        <!-- Page title - Bind to $state's title -->
                        <div class="navbar-item pull-left h5" ng-bind="$state.current.data.title" id="pageTitle"></div>

                        <!-- navbar right -->
                        <ul class="nav navbar-nav pull-right">
                            <?php if (!empty($this->numNot)): ?>
                                <li class="nav-item dropdown pos-stc-xs">
                                    <a class="nav-link" href data-toggle="dropdown">
                                        <i class="material-icons">&#xe7f5;</i>
                                        <span class="label label-sm up warn"><?= $this->numNot ?></span>
                                    </a>
                                    <div class="dropdown-menu pull-right w-xl animated fadeInUp no-bg no-border no-shadow">
                                        <?= $this->listNotifications ?>
                                    </div>
                                </li>
                            <?php endif; ?>
                            <li class="nav-item dropdown">
                                <a class="nav-link clear dropdown-toggle"
                                   data-toggle="dropdown" role="button"
                                   aria-haspopup="true" aria-expanded="false">
                                    <span class="avatar w-32">
                                        <?php $ruta = HTTP_PATH_ROOT . "recursos/img/user.png";
                                        if (!file_exists($ruta)) $ruta = "../framework/recursos/img/user.png"; ?>
                                        <img src="<?= $ruta ?>" alt="user">
                                        <i class="on b-white bottom"></i>
                                    </span>
                                </a>
                                <div class="dropdown-menu pull-right dropdown-menu-scale">
                                    <a class="dropdown-item"
                                       onclick="navegar('inicio')"><?= $this->idioma->topmenu->lblInicio ?></a>
                                    <a class="dropdown-item"
                                       onclick="btnMiPerfil()"><?= $this->idioma->topmenu->lblPerfil ?></a>
                                    <?php if (!$_SESSION["app"]): ?>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item"
                                           onclick="cerrarSesion()"><?= $this->idioma->topmenu->lblCerrarSesion ?></a>
                                    <?php endif; ?>
                                </div>
                            </li>
                        </ul>
                        <div class="collapse navbar-toggleable-sm" id="collapse">
                            <div class="navbar-form form-inline pull-right pull-none-sm navbar-item v-m">
                                <div class="form-group 1-h m-a-0">
                                    <div class="input-group">
                                        <a title="Inicio" onclick="navegar('inicio')" class="nav-link btn btn-sm btn-outline b-primary text-primary b-2x" style="border-color:#c0ca33 !important" data-toggle="dropdown">
                                            <i class="material-icons">home</i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div ui-view class="app-body" id="view">

                    <?php
                    $namespace = Globales::$namespace;
                    $floatingButton = HTTP_PATH_ROOT . "vista/floatingButton.phtml";
                    if (file_exists($floatingButton))
                        include_once $floatingButton;
                    else
                        include_once "../framework/vista/floatingButton.phtml";
                    ?>
                    <div class="hidden dropdown" id="divAcciones">
                        <a title="Reprogramar fecha"
                           class="bottom-20 md-btn md-fab md-fab-bottom-right2 pos-fix blue-500"
                           onclick="moverFechaLote()" id="btnacciones">
                            <i class="material-icons i-24 text-white">today</i>
                        </a>
                        <div class="quickMenu dropdown-menu text-color pull-right p-a-0 animated fadeInUp"
                             style="width:<?= !is_null($this->acciones) ? $this->acciones->ancho ?: 0 : 0 ?>px">
                            <div class="row no-gutter text-primary-hover">
                                <?= !is_null($this->acciones) ? $this->acciones->html : '' ?>
                            </div>
                        </div>
                    </div>
                    <?php endif; ?>

                    <?= $this->page ?>

                    <?php if ($vista != "login" and $vista != "registro"): ?>
                </div>
            </div>
            <!-- / -->
            <!-- ############ LAYOUT END-->
        <?php endif; ?>
        </div>
    </fieldset>
</form>
<form id="frmAside">
    <!-- right -->
    <div class="modal fade inactive" id="rightBar" data-backdrop="false">
        <div class="right w-xl b-l">
            <div class="navbar grey-100">
                <!--<h4 class="navbar-brand"><?= $this->idioma->lblTitulo ?></h4>-->
                <a id="btnCerrarAside" class="btn btn-danger btn-sm btnAside" onclick="cerrarAside()">
                    <i class="material-icons">close</i>
                </a>
            </div>
            <input type="hidden" id="txtAside" value="0">
            <div id="rightBarContent">
                <div class="loading"></div>
            </div>
        </div>
    </div>
    <input type='hidden' value='0' id='txtGuardado'>
</form>
<?= $this->scripts ?>
</body>
</html>
