<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 28/feb/2017
 * Time: 05:58 PM
 */
/** @var Perfiles $this */
?>
<div class="padding">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <div class="box">
                <div class="box-body">
                    <div class="form-group row">
                        <div class="col-md-2"></div>
                        <label for="txtNombre" class="col-md-2 form-control-label"><?= $this->idioma->lblNombre ?>
                            :</label>
                        <div class="col-md-6">
                            <input value="<?= $this->perfil->nombrePerfil ?>" id="txtNombre" name="nombre" type="text"
                                   class="form-control" placeholder="<?= $this->idioma->lblNombre ?>">
                        </div>
                        <div class="col-md-2"></div>
                    </div>
                    <div class="form-group row">
                        <div class="dd nestable">
                            <ol class="dd-list">
                                <?= $this->arbolPermisos ?>
                            </ol>
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-3 submit">
                            <a onclick="navegar('perfiles')"
                               class="btn btn-danger col-md-5"><?= $this->idioma->btnCancelar ?></a>
                            <a onclick="btnGuardar(<?= $this->perfil->idPerfil ?>)"
                               class="btn btn-primary col-md-5"><?= $this->idioma->btnGuardar ?></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



