<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 16/may/2017
 * Time: 12:28 PM
 */
/** @var MiPerfil $this */
?>
<div class="col-lg-4"></div>
<div class="col-md-6 col-lg-4">
    <nav class="navside white r m-b">
        <div class="nav-border b-primary" flex>
            <div class="box" style="box-shadow: 0 0 0; margin-bottom:0;">
                <div class="box-body">
                    <div class="form-horizontal container">
                        <div class="form-group row">
                            <div class="col-xs-12">
                                <h4>Datos de la cuenta</h4>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-xs-12">
                                <h5>Agente: <?= $this->agente->nombre ?></h5>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-xs-12" style="text-transform: none;">
                                <h5>Correo del Agente: <?= $this->agente->correo ?></h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>