<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 27/abr/2017
 * Time: 04:36 PM
 */
/** @var MiPerfil $this */
$this->idioma = Globales::getIdioma('miperfil');
?>
<div class="col-lg-4"></div>
<div class="col-md-6 col-lg-4">
    <nav class="navside white r m-b">
        <div class="nav-border b-primary" flex>
            <div class="box" style="box-shadow: 0 0 0; margin-bottom:0;">
                <div class="box-body">
                    <div class="form-horizontal container">
                        <div class="form-group row">
                            <div class="col-xs-12">
                                <h4><?= $this->idioma->lblTitulo ?></h4>
                            </div>
                        </div>
                        <div class="md-form-group float-label">
                            <input readonly value="<?= $this->correo ?>" name="email" type="email" class="md-input has-value"
                                   required>
                            <label><?= $this->idioma->lblEmail ?></label>
                        </div>
                        <div class="row text-center">
                            <div class="col-sm-12">
                                <div class="box-color warn text-color pos-rlt">
                                    <span class="arrow bottom b-warn"></span>
                                    <div class="box-body">
                                        Dejar ambos campos en blanco para no modificar la contrase&ntilde;a
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="navheader">
                            <small class="text-muted">
                                <?= $this->idioma->lblReestablecer ?>
                            </small>
                        </div>
                        <div class="md-form-group float-label">
                            <input name="password" type="password" class="md-input">
                            <label><?= $this->idioma->lblPassword ?></label>
                        </div>
                        <div class="md-form-group float-label">
                            <input name="repassword" type="password" class="md-input">
                            <label><?= $this->idioma->lblRePassword ?></label>
                        </div>
                        <div class="md-form-group float-label">
                            <label class="form-control-label">Sucursal</label>
                            <select name="selectSucursal" id="selectSucursal" class="form-control">
                                <option value="0" disabled selected>Seleccione un almacen</option>
                                <?= $this->listaSucursales ?>
                            </select>
                        </div>
                        <div flex-no-shrink>
                            <nav ui-nav>
                                <div class="navbar">
                                    <a onclick="btnGuardar()"
                                       class="btn blue-500 btn-sm btnAside"><?= $this->idioma->btnGuardar ?></a>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</div>
