<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 24/feb/2017
 * Time: 11:30 AM
 */
/** @var Usuarios $this */

?>
<div class="padding">
    <div class="row">
        <div class="col-md-12">
            <div class="box">
                <div class="box-body">
                    <div class="form-group row">
                        <label for="txtNombre"
                               class="col-sm-2 form-control-label"><?= $this->idioma->lblNombre ?></label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" value="<?= $this->usuario->nombre ?>"
                                   name="nombre" id="txtNombre" placeholder="<?= $this->idioma->lblNombre ?>">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="txtUsuario"
                               class="col-sm-2 form-control-label"><?= $this->idioma->lblUsuario ?></label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control"
                                   value="<?= $this->usuario->login ?>" <?= isset($this->usuario) ? "readonly" : "" ?>
                                   name="usuario" id="txtUsuario" placeholder="<?= $this->idioma->lblUsuario ?>">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="txtEmail"
                               class="col-sm-2 form-control-label"><?= $this->idioma->lblCorreo ?></label>
                        <div class="col-sm-10">
                            <input type="email" class="form-control" value="<?= $this->usuario->correo ?>"
                                   name="email" id="txtEmail" placeholder="<?= $this->idioma->lblCorreo ?>">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="txtPass"
                               class="col-sm-2 form-control-label"><?= $this->idioma->lblPassword ?></label>
                        <div class="col-sm-10">
                            <input required type="password" class="form-control"
                                   name="password" id="txtPass" placeholder="<?= $this->idioma->lblPassword ?>">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="txtRePass"
                               class="col-sm-2 form-control-label"><?= $this->idioma->lblRePassword ?></label>
                        <div class="col-sm-10">
                            <input required type="password" class="form-control"
                                   name="repass" id="txtRePass" placeholder="<?= $this->idioma->lblRePassword ?>">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="selectPerfil"
                               class="col-sm-2 form-control-label"><?= $this->idioma->lblPerfil ?></label>
                        <div class="col-sm-10">
                            <select name="perfil" id="selectPerfil" class="form-control c-select select2">
                                <?= $this->listaPerfiles ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="selectEspecialista" class="col-sm-2 for-control-label">Especialista</label>
                        <div class="col-sm-10">
                            <select name="especialista" id="selectEspecialista" class="form-control c-select select2">
                                <option selected disabled value="0">Especialista</option>
                                <?= $this->listaEspecialistas; ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row m-t-md">
                        <div class="col-md-3 submit">
                            <a class="btn btn-danger col-md-5"
                               onclick="navegar('usuarios')"><?= $this->idioma->btnCancelar ?></a>
                            <a class="btn btn-primary col-md-5"
                               onclick="btnGuardar(<?= $this->usuario->id ?>)"><?= $this->idioma->btnRegistrar ?></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
