<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 11/may/2017
 * Time: 10:15 AM
 */
?>

<div class="center-block w-xxl w-auto-xs">
    <div class="p-a-md box-color r text-color m-a">
        <div class="md-form-group float-label">
            <input name="email" type="email" class="md-input" required>
            <label><?= $this->idioma->lblEmail ?></label>
        </div>
        <div>
            <a onclick="ajax('enviarPassword');"
               class="btn lime-600 btn-block p-x-md"><?= $this->idioma->btnEnviar ?></a>
        </div>
    </div>
</div>